config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'
  get "/users/:id", to: "account#show", as: "user_account"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :hat, presence: true
  validates :content_post, presence: true

  mount_uploader :thumbnail, ThumbnailUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def show
    @user = User.find params[:id]
    @posts = Post.where(@user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :load_photo, only: [:show, :edit, :update, :destroy]
   before_action :required, only:[:edit, :update, :destroy]
  def index
    @posts = Post.all.order(created_at: :desc)
    @users = User.all
  end

  def show
    @user = User.find(@post.user_id)
  end

  def update
      if @post.update_attributes authorized_attributes
          redirect_to @post
      else
          render "edit"
      end
  end

  def new
    @post = Post.new
  end

  def destroy
        Post.destroy(@post.id)
        redirect_to :posts
    end

  def create
        @post = Post.new authorized_attributes
        @post.user = current_user
        if @post.save
            redirect_to @post
        else
            render "new"
        end
    end

    def load_photo
        @post = Post.find params[:id]
    end

    def required
      if @post.user_id.to_f != current_user
        redirect_to('/')
      end
    end

    def authorized_attributes
      authorized_attributes = params.require(:post).permit(
          :title,
          :content_post,
          :hat,
          :thumbnail
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'News', :posts ,:class=>"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active"><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, :class=>"nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Se connecter', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f|%>
            <div class="mdl-cell mdl-cell--6-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <%= f.label :title %>
                <%= f.text_field :title %>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <%= f.label :thumbnail%>
                <%= f.file_field :thumbnail %>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <%= f.label :hat%>
                <%= f.text_area :hat %>
            </div>
            <div class="mdl-cell mdl-cell--6-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <%= f.label :content_post%>
                <%= f.text_area :content_post %>
            </div>
            <div class="mdl-cell mdl-cell--6-col">
            <%= f.submit %>
            <%= link_to "Cancel", posts_path%>
            </div>
        <% end %>

app/views/posts/index.html.erb
<div class="container">
  <h1 style="text-align: center">Les News</h1>
  <% if user_signed_in? %>
    <div class="new_post">
      <%= link_to 'Creer nouveau post', new_post_path %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <div class="col-sm-12">
        <% @posts.all.each do |post| %>
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= post.thumbnail %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.hat %></p>
            <p class="card-text">Créer le : <%= post.created_at %></p>
            <% @user= @users.find_by id: post.user_id %>
            <p class="card-text">Auteur : <%= @user.first_name %> <%= @user.last_name %></p>
            <%= link_to "Détails", post_path(post.id), :class=>"btn btn-primary" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f|%>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title , class:"form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :thumbnail%>
        <%= f.file_field :thumbnail, class:"form-control-file" %>
    </div>
    <div class="form-group">
        <%= f.label :hat%>
        <%= f.text_area :hat , class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :content_post%>
        <%= f.text_area :content_post , class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create", class:"btn btn-primary"  %>
      <%= link_to "Cancel", posts_path%>
    </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="card mb-3 mt-5">
      <img src="<%= @post.thumbnail%>" alt="Card image cap" style="height: 18em">
      <div class="card-body">
        <h5 class="card-title"><%= @post.title %></h5>
        <p>Auteur : <%= link_to @user.first_name, user_account_path(@post.user_id), class:"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %></p>
        <p class="card-text"><%= @post.hat %></p>
        <p class="card-text"><%= @post.content_post %> </p>
        <%= link_to "Back", posts_path, class:"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
        <% if current_user == @post.user_id %>
          <%= link_to "Modify", edit_post_path(@post.id), class:"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
          <%= link_to "Delete", post_path(@post.id), method: :delete, confirm: "Are you sure ?",class:"mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
        <% end %>
      </div>
    </div>
  </div>
</div>